formatter: markdown

output:
  file: README.md
  mode: replace
  template: |-
    # terraform-postgresql-bootstrap

    Terraform module to provision and manage postgresql resources.   

    ## Usage

    ```hcl
      module "bootstrap_db" {
        source = "./"

        extensions = ["pg_stat_statements", "pg_hint_plan"]

        databases = [
          {
            name = "test"
          }
        ]

        roles = [
          {
            name                = "test"
            database            = "test"
            database_privileges = "CONNECT,CREATE,TEMPORARY"
            table_privileges    = "SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER"
            sequence_privileges = "USAGE,SELECT,UPDATE"
          },

          {
            name                = "test-ro"
            database            = "test"
            database_privileges = "CONNECT"
            table_privileges    = "SELECT"
            sequence_privileges = "USAGE,SELECT"
          },

          {
            name                = "prometheus-exporter"
            roles               = "pg_read_all_stats,pg_read_all_settings"
            database            = "test"
            database_privileges = "CONNECT"
          }
        ]
      }
    ```

    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS --> 

    ## License
    The Apache-2.0 license

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true